name: 'Sloppy'
description: 'Relentless AI code cleanup. Scans free, fixes with your API key.'
author: 'Braeden Saunders'

branding:
  icon: 'zap'
  color: 'yellow'

inputs:
  github-token:
    description: 'GitHub token for API access and GitHub Models'
    required: false
    default: ${{ github.token }}
  mode:
    description: 'scan (free, report only) or fix (BYOK, auto-fix + PR)'
    required: false
    default: ''
  agent:
    description: 'AI agent to use: claude or codex'
    required: false
    default: 'claude'
  timeout:
    description: 'Max run time (e.g. 30m, 2h, 5h50m)'
    required: false
    default: '30m'
  max-cost:
    description: 'Max API spend per run (e.g. $5.00)'
    required: false
    default: '$5.00'
  max-passes:
    description: 'Max scan/fix passes before stopping'
    required: false
    default: '10'
  min-passes:
    description: 'Minimum passes to confirm repo is clean'
    required: false
    default: '2'
  max-chains:
    description: 'Max self-continuations for long runs (6h each)'
    required: false
    default: '3'
  strictness:
    description: 'Issue detection strictness: low, medium, high'
    required: false
    default: 'high'
  fix-types:
    description: 'Comma-separated issue types to fix'
    required: false
    default: 'security,bugs,types,lint,dead-code,stubs,duplicates,coverage'
  model:
    description: 'Override AI model (e.g. claude-sonnet-4-5-20250929)'
    required: false
    default: ''
  github-models-model:
    description: 'Model for scan via GitHub Models (free: openai/gpt-4o-mini, premium: openai/gpt-4o, openai/o1-mini, etc.)'
    required: false
    default: 'openai/gpt-4o-mini'
  test-command:
    description: 'Custom test command (auto-detected if empty)'
    required: false
    default: ''
  gist-id:
    description: 'GitHub Gist ID for dynamic badge updates'
    required: false
    default: ''
  gist-token:
    description: 'PAT with gist scope for badge updates'
    required: false
    default: ''
  fail-below:
    description: 'Fail the action if score drops below this'
    required: false
    default: '0'
  verbose:
    description: 'Stream agent output to the Actions log in real-time'
    required: false
    default: 'false'
  max-turns:
    description: 'Max agent turns per invocation (scan: 30, fix: 15)'
    required: false
    default: ''
  max-issues-per-pass:
    description: 'Max issues to fix per pass (0 = unlimited)'
    required: false
    default: '0'
  output-file:
    description: 'Write full issues JSON to this path (e.g. .sloppy/issues.json). Empty to disable.'
    required: false
    default: ''
  scan-scope:
    description: 'What to scan: auto (PR files on pull_request, full otherwise), pr (PR files only), full (entire repo)'
    required: false
    default: 'auto'
  custom-prompt:
    description: 'Custom instructions injected into every scan/fix prompt (inline text)'
    required: false
    default: ''
  custom-prompt-file:
    description: 'Path to a file containing custom prompt instructions (relative to repo root)'
    required: false
    default: ''
  plugins:
    description: 'Enable/disable the plugin system (loads from .sloppy/plugins/)'
    required: false
    default: 'true'
  parallel-agents:
    description: 'Number of parallel agents to dispatch for fixing (1-8). Uses git worktrees for true parallelism.'
    required: false
    default: '1'
  chain_number:
    description: 'Internal: chain continuation number'
    required: false
    default: '0'

outputs:
  score:
    description: 'Code quality score (0-100)'
  score-before:
    description: 'Score before fixes were applied'
  issues-found:
    description: 'Total issues found'
  issues-fixed:
    description: 'Total issues fixed'
  pr-url:
    description: 'URL of the created pull request'
  summary-url:
    description: 'URL to the Job Summary with full results'
  output-file:
    description: 'Path to the issues JSON file (if output-file was configured)'

runs:
  using: 'node20'
  main: 'dist/index.js'
